# Actuator
#management.server.port=9090
#management.endpoints.web.base-path=/observability
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# Redis
spring.data.redis.host = localhost
spring.data.redis.port = 6379
spring.data.redis.timeout = 2s

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
kafka.topic.name=initial-topic

# Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Consumer
spring.kafka.consumer.group-id=consumer-group-01
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
