package com.lambdatrix.ecom.common.events.types;

public enum DomainEventType {
  PRODUCT_CREATED,
  PRODUCT_UPDATED,
  STOCK_RESERVED,
  STOCK_RELEASED,
  ORDER_CREATED,
  ORDER_CONFIRMED,
  ORDER_CANCELLED,
  PAYMENT_AUTHORIZED,
  PAYMENT_FAILED,
  SHIPMENT_CREATED,
  SHIPMENT_STATUS_CHANGED,
  NOTIFICATION_CREATED,
  AUDIT_RECORDED
}
